import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import Contact from '../components/Contact'
import Main from '../components/Main'
import Navbar from '../components/Navbar'
import Portfolio from '../components/Portfolio'
import Social from '../components/Social'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Bipin | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Qwitcher+Grypen&display=swap" rel="stylesheet"/>
        <link href="https://api.fontshare.com/v2/css?f[]=satoshi@901&f[]=supreme@800&display=swap" rel="stylesheet"/>
      </Head>
      <Navbar/>
      <Social/>
      <Main/>
      <About/>
      <Portfolio/>
      <Contact/>
      
      </>
  )
}
